<a href="https://colab.research.google.com/github/yejin0455/sesac-ML/blob/main/D09_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%run my_init.py

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%matplotlib inline

In [ ]:
from sklearn.ensemble import VotingClassifier, BaggingClassifier, \
                             RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import cross_validate, GridSearchCV
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [ ]:
obj = load_breast_cancer()
print(f"feature_name:{obj.feature_names.shape}\n{obj.feature_names}", end="\n\n")
print(f"data:{obj.data.shape}\n{obj.data}", end="\n\n")
print(f"target_names:{obj.target_names.shape}\n{obj.target_names}", end="\n\n")
print(f"target:{obj.target.shape}\n{obj.target}", end="\n\n")

feature_name:(30,)
['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']

data:(569, 30)
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]

t

In [ ]:
X, y = load_breast_cancer(return_X_y=True)
print(f"X:{X.shape}\n{X}", end="\n\n")
print(f"y:{y.shape}\n{y}", end="\n\n")

X:(569, 30)
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]

y:(569,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train.shape, y_train.shape

((455, 30), (455,))

In [ ]:
X_test.shape, y_test.shape

((114, 30), (114,))

In [ ]:
lr = LogisticRegression()
knn = KNeighborsClassifier()
dt = DecisionTreeClassifier()
vt = VotingClassifier([('LR', lr), ('KNN', knn)], )
bg = BaggingClassifier(dt, 100)
rf = RandomForestClassifier()

In [ ]:
for clf in [lr, knn, vt, dt, bg, rf]:
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  print(f"{clf.__class__.__name__}: {accuracy_score(y_test, y_pred):.4f}")

LogisticRegression: 0.9649
KNeighborsClassifier: 0.9561
VotingClassifier: 0.9737
DecisionTreeClassifier: 0.9298
BaggingClassifier: 0.9561
RandomForestClassifier: 0.9649


In [ ]:
wine = pd.read_csv("https://bit.ly/wine_csv_data")
wine.head(3)

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0

In [ ]:
data = wine.drop('class', axis=1).to_numpy()
data.shape

(6497, 3)

In [ ]:
target = wine['class'].to_numpy()
target.shape

(6497,)

In [ ]:
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

In [ ]:
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target, n_jobs=-1, return_train_score=True, cv=5)

In [ ]:
scores['train_score']

array([0.9971133 , 0.99663219, 0.9978355 , 0.9973545 , 0.9978355 ])

In [ ]:
scores['test_score'] # validation score

array([0.88461538, 0.88942308, 0.90279115, 0.88931665, 0.88642926])

In [ ]:
np.mean(scores['test_score'])

0.8905151032797809

In [ ]:
rf.fit(train_input, train_target)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [ ]:
rf.feature_importances_

array([0.23167441, 0.50039841, 0.26792718])

In [ ]:
rf.predict(test_input)

array([1., 0., 1., ..., 1., 1., 1.])

In [ ]:
rf.predict_proba(test_input)

array([[0.  , 1.  ],
       [0.85, 0.15],
       [0.02, 0.98],
       ...,
       [0.11, 0.89],
       [0.  , 1.  ],
       [0.01, 0.99]])

In [ ]:
accuracy_score(test_target, rf.predict(test_input))

0.8892307692307693

In [ ]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)

RandomForestClassifier(n_jobs=-1, oob_score=True, random_state=42)

In [ ]:
rf.oob_score_

0.8934000384837406

In [ ]:
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs=-1)

In [ ]:
scores['train_score']

array([0.9971133 , 0.99663219, 0.998076  , 0.997595  , 0.9978355 ])

In [ ]:
np.mean(scores['test_score'])

0.8887848893166506

In [ ]:
et.fit(train_input, train_target)
et.feature_importances_

array([0.20183568, 0.52242907, 0.27573525])

In [ ]:
gb = GradientBoostingClassifier(random_state=42)
gb.fit(train_input, train_target)

GradientBoostingClassifier(random_state=42)

In [ ]:
accuracy_score(train_target, gb.predict(train_input))

0.8880123147969983

In [ ]:
accuracy_score(test_target, gb.predict(test_input))

0.8669230769230769

In [ ]:
params = {
    "learning_rate": [0.05, 0.1, 0.5],
    'n_estimators': [500, 1000, 5000],
    'subsample': [0.1, 0.2, 0.5, 1]
}

In [ ]:
gs = GridSearchCV(GradientBoostingClassifier(random_state=42), params, n_jobs=-1, cv=3)
gs.fit(train_input, train_target)

GridSearchCV(cv=3, estimator=GradientBoostingClassifier(random_state=42),
             n_jobs=-1,
             param_grid={'learning_rate': [0.05, 0.1, 0.5],
                         'n_estimators': [500, 1000, 5000],
                         'subsample': [0.1, 0.2, 0.5, 1]})

In [ ]:
gs.best_score_

0.8797390420168739

In [ ]:
gs.best_params_

{'learning_rate': 0.2, 'n_estimators': 1000}

In [ ]:
gb = gs.best_estimator_
accuracy_score(test_target, gb.predict(test_input))

0.8769230769230769

In [ ]:
gb.feature_importances_

array([0.1648851 , 0.66776294, 0.16735196])

In [ ]:
xgb = XGBClassifier(random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True)

In [ ]:
scores["train_score"]

array([0.88717825, 0.88092374, 0.87854738, 0.88480038, 0.88239538])

In [ ]:
scores["test_score"]

array([0.85673077, 0.87019231, 0.89220404, 0.86236766, 0.87295476])

In [ ]:
lgbm = LGBMClassifier(random_state=42)
scores = cross_validate(lgbm, train_input, train_target, return_train_score=True)

In [ ]:
scores["train_score"]

array([0.93312485, 0.93432764, 0.93217893, 0.93241943, 0.93698894])

In [ ]:
scores["test_score"]

array([0.86442308, 0.88076923, 0.90856593, 0.86429259, 0.87680462])